#!/bin/sh
maps=~/.wine/drive_c/GOG\ Games/HoMM\ 4\ Complete/maps

backup() {
	filename=$1
	cp "$maps/$filename" "./$filename"
}

backup AA\ Emperor\'s\ Treasure\ Test.h4c
backup Ben\'s\ Map\ 1.h4c
backup Castles\ of\ Annuvin.h4c
